// Google Drive URLs for BetterWLPRS Gallery (965 wallpapers)
const driveWallpapers = [
    "https://drive.google.com/uc?export=view&id=10sU-qBU2KF60SVwzK0JNjenANjVGR3yE",
    "https://drive.google.com/uc?export=view&id=1Ekt_csiuE7-iKKCvd2JvJWDGYingi2FG",
    "https://drive.google.com/uc?export=view&id=1HxVzouXQ8Dj7tNMmu11dOok1Exd_aoD1",
    "https://drive.google.com/uc?export=view&id=1OIjNurj4S4mPsFmSUn28FcS5S0eljKZo",
    "https://drive.google.com/uc?export=view&id=1V_tafR17JAfIniXOTtnD4DdQIhmPbFSX",
    "https://drive.google.com/uc?export=view&id=1_CxM37uZQsSmZOXiQT2VGP-tpsRQhJP2",
    "https://drive.google.com/uc?export=view&id=1fHCuFGv6QhCOAesoxtC8N0NQuKXEVGpW",
    "https://drive.google.com/uc?export=view&id=1r64PUOKb3DO2VuLcPkAGY6chkBLFrkhI",
    "https://drive.google.com/uc?export=view&id=1xKP-eNkjX2_P-Ciwpypsk28duZqxzBGJ",
    "https://drive.google.com/uc?export=view&id=1HxBTi6lWnpAWwOYnVe_dnoxct6OiwW75",
    "https://drive.google.com/uc?export=view&id=1UblVsWe2Z9A0Dp8MYzYThOGE8mw_1o4Z",
    "https://drive.google.com/uc?export=view&id=1rpFnDO8_Sn6ZqcdMaey8IseuK3HszPYx",
    "https://drive.google.com/uc?export=view&id=1IzeBwia5xqSviiykAl8zi8tbJuNQ0cIW",
    "https://drive.google.com/uc?export=view&id=1zyRCQEh4awhSiH_0T-NfdrfWhoTjhZkH",
    "https://drive.google.com/uc?export=view&id=1vOH16O4Spg0I_-6KbbH41N-r8QuMnPqy",
    "https://drive.google.com/uc?export=view&id=15P5ppwbxE7UngobNUhKOZ71dGAnpQSLx",
    "https://drive.google.com/uc?export=view&id=1Sgd413Z7HDvO3AXa4WnpQvJ7pnjjR06T",
    "https://drive.google.com/uc?export=view&id=1DR10UgQONA0eaz1Ded8IYykZXmTy_2ki",
    "https://drive.google.com/uc?export=view&id=1mcSbNPsNj86ANQexfRhr9-nXxzt1jRj9",
    "https://drive.google.com/uc?export=view&id=1gPIRW4wRlDsmNm5qnSeAAFLuBPtLCYvq",
    "https://drive.google.com/uc?export=view&id=1L7k6WVqu7G3tbJA3G3MByRkDqVZvLTMe",
    "https://drive.google.com/uc?export=view&id=10-ZScxnvwTj5AGz4IoqSW6_xoVFugCgx",
    "https://drive.google.com/uc?export=view&id=1_ykeEr4GhUk3pkVujzUxjdO2hlR5hzY9",
    "https://drive.google.com/uc?export=view&id=1t4cSxnwKXSTrHTrOV2StC0yG4m0PYGcb",
    "https://drive.google.com/uc?export=view&id=1i6kvmCHyaQysKYU3NN3e2gn33WCBPgSp",
    "https://drive.google.com/uc?export=view&id=1HCaD1sSrJ8a8QpwbukY7cnFgd2peRFBb",
    "https://drive.google.com/uc?export=view&id=1ZIsxN5-zYYUqGUd_7VY8_sPgEomBBicw",
    "https://drive.google.com/uc?export=view&id=1unSUXRW3SOiypc0deik8HyI97oqj6oFP",
    "https://drive.google.com/uc?export=view&id=1-6qnU8hdHK9hb3VT1gK-e01xdNssKaTf",
    "https://drive.google.com/uc?export=view&id=1qqswIqklOBg12bw65LIammDOoeNJ-TMX",
    "https://drive.google.com/uc?export=view&id=1xjLWsgKyTSw8Y-FrclUsk_GSeOd2LFX5",
    "https://drive.google.com/uc?export=view&id=1IhjuriMKChH-x67hpn9KxDM_4X9Xr6eJ",
    "https://drive.google.com/uc?export=view&id=1Mf-mYvtGraV1VUCgq6Bf8KboAuztO9KG",
    "https://drive.google.com/uc?export=view&id=1jY9Um7-t-Ekr-DcqtBXbGc9h4hn6m38d",
    "https://drive.google.com/uc?export=view&id=1o4wsN9623Ll_FwMWOsStX4WGu9Ug2hK_",
    "https://drive.google.com/uc?export=view&id=1rSFfDHDX4-mKUf_6LNfhiy9pG64U4_wO",
    "https://drive.google.com/uc?export=view&id=1qRgCmbyOZAOPzWRhnNT8CYoetZZ3yHoi",
    "https://drive.google.com/uc?export=view&id=19EeG4zRUTX10Bk-4uLsxqg6z2HLYy0ex",
    "https://drive.google.com/uc?export=view&id=1etwgIiZj-HKjIGoXoZmcp5QxrxUI_9Ov",
    "https://drive.google.com/uc?export=view&id=1BQU_k5clLNu7ekqR0TbOZijhyIzbeie8",
    "https://drive.google.com/uc?export=view&id=1P09XH0U8PIewnebtHlHIOBgMwn7BgGnA",
    "https://drive.google.com/uc?export=view&id=1p58akSj7IqaWnHGcrO9tzptLOOE4RsGK",
    "https://drive.google.com/uc?export=view&id=17T4y12tiRII4anQBA0FB5ntK0HsyWxkD",
    "https://drive.google.com/uc?export=view&id=1FFr9TVXzBrfg0uBEVZFH-JkO5JIM7Lco",
    "https://drive.google.com/uc?export=view&id=1M_6sfV3A4XB7XVaTe7AjmH7GrB6HtjRw",
    "https://drive.google.com/uc?export=view&id=1Gq9boaMpTueYGUjmOqJ3kOvCt3LYlS2a",
    "https://drive.google.com/uc?export=view&id=19P1yA4bVoMbAARM5XPEeeZP1PDeFI9B8",
    "https://drive.google.com/uc?export=view&id=1LV6WKwO5C7IoHVET55rKnUMFiO9wb7bh",
    "https://drive.google.com/uc?export=view&id=1Nl9utx9ASQOXx7Lq_ievtnyT-fp3AnXX",
    "https://drive.google.com/uc?export=view&id=1xk-8VwPkTgrDyQ49bcJ02rwnIg-2-BpK",
    "https://drive.google.com/uc?export=view&id=1Wzp8v8RPJzXLs4osSfZ3QlZH3vCDfiOs"
];

// Add the rest of the URLs - truncated for brevity in this example
// The full array contains all 965 URLs from your Google Drive folder