/* Entorno — territorio piloto: Barcelona metropolitana (BCN · Hospitalet · Collserola al borde).
   Contenido verificado editorialmente. Imágenes: usar wikimediaSearch / imageQuery más adelante. */
window.ENTORNO_TERRITORY = {
  id: 'bcn-metro',
  name: 'Barcelona metropolitana',
  places: ['Barcelona', "L'Hospitalet de Llobregat", 'Collserola', 'Llobregat'],
  blurb: 'Lo que canta, crece y se cuela entre asfalto, parques y la sierra de al lado.'
};

window.ENTORNO_SPECIES = [
  {
    id: 'platano-sombra',
    name: 'Plátano de sombra',
    alias: 'El de las avenidas',
    guild: 'arboles',
    latin: 'Platanus × hispanica',
    image: './img/species/platano-sombra.jpg',
    season: 'Todo el año',
    where: 'Paseos y avenidas: Rambla, paseos anchos, alineaciones de Hospitalet.',
    hook: 'Si hay sombra de verdad en agosto, casi seguro es él.',
    signals: [
      'Tronco moteado que se pela en placas claras',
      'Hojas grandes con varias puntas',
      'Bolitas colgando en otoño-invierno'
    ],
    tip: 'Mira el tronco: el camuflaje blanco-gris es su firma.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Dominante del arbolado viario en Barcelona y Hospitalet.',
    sources: ['CREAF - fenología arbolado BCN', 'Plan de Gestión del Arbolado de Barcelona'],
    imageQuery: 'Platanus hispanica white bark street tree',
    wikimediaSearch: 'Platanus acerifolia',
    imageNotes: 'Tronco moteado, hoja palmada, frutos redondos.'
  },
  {
    id: 'almez',
    name: 'Almez',
    alias: 'El elegante',
    guild: 'arboles',
    latin: 'Celtis australis',
    image: './img/species/almez.jpg',
    season: 'Todo el año',
    where: 'Calles secundarias, plazas y parques de BCN y Hospitalet.',
    hook: 'Pasa desapercibido hasta que miras la hoja: asimétrica, y listo.',
    signals: [
      'Hojas pequeñas con base torcida',
      'Corteza gris relativamente lisa',
      'Copa redonda y limpia'
    ],
    tip: 'Compara las dos mitades de la hoja: una empieza más arriba que la otra.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Muy plantado en ciudad; aguanta sequía y aire urbano.',
    sources: ['CREAF', 'Plan de Gestión del Arbolado de Barcelona'],
    imageQuery: 'Celtis australis asymmetrical leaves',
    wikimediaSearch: 'Celtis australis',
    imageNotes: 'Hoja asimétrica y copa redondeada.'
  },
  {
    id: 'tipuana',
    name: 'Tipuana',
    alias: 'Lluvia amarilla',
    guild: 'arboles',
    latin: 'Tipuana tipu',
    image: './img/species/tipuana.jpg',
    season: 'Floración mayo–junio',
    where: 'Avenidas y parques del Eixample, Montjuïc y zona metro.',
    hook: 'En junio la acera se tiñe de confeti dorado.',
    signals: [
      'Racimos densos de flores amarillas',
      'Hojas compuestas finas',
      'Frutos alados (sámaras)'
    ],
    tip: 'Si el suelo está amarillo en junio, levanta la vista.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Menos abundante que el plátano, pero imborrable en flor.',
    sources: ['CREAF - Tipuana fenología'],
    imageQuery: 'Tipuana tipu yellow flowers tree',
    wikimediaSearch: 'Tipuana tipu',
    imageNotes: 'Flor amarilla en masa y hojas pinnadas.'
  },
  {
    id: 'jacaranda',
    name: 'Jacarandá',
    alias: 'Violeta de mayo',
    guild: 'arboles',
    latin: 'Jacaranda mimosifolia',
    image: './img/species/jacaranda.jpg',
    season: 'Floración abril–mayo',
    where: 'Calles soleadas del Eixample, Diagonal y jardines abiertos.',
    hook: 'Una semana al año la ciudad se pone lila. Esa eres tú.',
    signals: [
      'Nubes de flores azul-moradas',
      'Hojas finísimas tipo helecho',
      'Vainas leñosas planas'
    ],
    tip: 'No dure mucho: hay que pillarlo en flor.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Icónico en BCN; menos denso que plátano/almez, muy visible en primavera.',
    sources: ['CREAF - Guía fenológica'],
    imageQuery: 'Jacaranda mimosifolia purple flowers',
    wikimediaSearch: 'Jacaranda mimosifolia',
    imageNotes: 'Flor violeta y follaje fino.'
  },
  {
    id: 'olivo',
    name: 'Olivo',
    alias: 'El de siempre',
    guild: 'arboles',
    latin: 'Olea europaea',
    image: './img/species/olivo.jpg',
    season: 'Todo el año',
    where: 'Jardines, patios, rotondas “mediterráneas” y Collserola bajo.',
    hook: 'Plata en la hoja. Cultura en raíz. Mediterráneo en maceta o en finca.',
    signals: [
      'Hojas plateadas por el envés',
      'Tronco retorcido con la edad',
      'Aceitunas en otoño'
    ],
    tip: 'Si huele a “jardín mediterráneo”, empieza por aquí.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Muy plantado en jardinería urbana; también silvestre en Collserola.',
    sources: ['Flora Catalana', 'Parc de Collserola'],
    imageQuery: 'Olea europaea olive tree silver leaves',
    wikimediaSearch: 'Olea europaea',
    imageNotes: 'Hoja plateada y tronco nudoso.'
  },
  {
    id: 'laurel',
    name: 'Laurel',
    alias: 'El de la cocina',
    guild: 'arboles',
    latin: 'Laurus nobilis',
    image: './img/species/laurel.jpg',
    season: 'Todo el año',
    where: 'Setos, patios, jardines y sotobosque de Collserola.',
    hook: 'Si rompes una hoja y huele a sofrito, bingo.',
    signals: [
      'Hojas duras y aromáticas',
      'Flores crema discretas en primavera',
      'Bayas oscuras'
    ],
    tip: 'A veces va podado como seto: sigue siendo laurel.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Común en jardinería y en zonas sombrías de Collserola.',
    sources: ['Flora Catalana'],
    imageQuery: 'Laurus nobilis bay laurel leaves',
    wikimediaSearch: 'Laurus nobilis',
    imageNotes: 'Hojas coriáceas aromáticas en primer plano.'
  },
  {
    id: 'palmera-canaria',
    name: 'Palmera canaria',
    alias: 'La de postal',
    guild: 'arboles',
    latin: 'Phoenix canariensis',
    image: './img/species/palmera-canaria.jpg',
    season: 'Todo el año',
    where: 'Paseos, plazas y frente marítimo; también entradas “de hotel”.',
    hook: 'Tronco grueso, corona densa: la palmera que sale en la foto.',
    signals: [
      'Estípite grueso y rugoso',
      'Hojas pinnadas enormes en corona',
      'Racimos de dátiles'
    ],
    tip: 'Si ves coronas secas o caídas, puede haber picudo: observa, no toques.',
    markKinds: ['vi'],
    confidence: 'medium',
    localNote: 'Menos “viario común” que plátano/almez, pero muy visible. Afectada por picudo rojo.',
    sources: ['Barcelona.cat - árboles de interés'],
    imageQuery: 'Phoenix canariensis palm Barcelona',
    wikimediaSearch: 'Phoenix canariensis',
    imageNotes: 'Tronco robusto y corona amplia.'
  },
  {
    id: 'pino-alepo',
    name: 'Pino de Alepo',
    alias: 'El del horizonte',
    guild: 'arboles',
    latin: 'Pinus halepensis',
    image: './img/species/pino-alepo.jpg',
    season: 'Todo el año',
    where: 'Collserola, Montjuïc, falda forestal y parques secos.',
    hook: 'Si el perfil del monte es un pino, casi seguro es este.',
    signals: [
      'Acículas en pares, flexibles',
      'Piñas ovoides',
      'Corteza parda en adultos'
    ],
    tip: 'Toca las agujas: flexibles, no rígidas. Huele a resina.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Dominante en Collserola/Montjuïc; no es el árbol típico de acera.',
    sources: ['Parc de Collserola', 'CREAF'],
    imageQuery: 'Pinus halepensis Aleppo pine',
    wikimediaSearch: 'Pinus halepensis',
    imageNotes: 'Silueta de pino mediterráneo y piñas.'
  },
  {
    id: 'hiedra',
    name: 'Hiedra',
    alias: 'La que trepa',
    guild: 'plantas',
    latin: 'Hedera helix',
    image: './img/species/hiedra.jpg',
    season: 'Todo el año',
    where: 'Muros, fachadas viejas, bases de árboles y vallas.',
    hook: 'Si una pared se ha comido el verde, suele ser ella.',
    signals: [
      'Hojas lobuladas brillantes en tallos jóvenes',
      'Raíces adhesivas en el muro',
      'Bayas oscuras en invierno'
    ],
    tip: 'En Gótico y fachadas antiguas del Eixample está casi de serie.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Muy extendida; da refugio a invertebrados y aves.',
    sources: ['Flora Catalana'],
    imageQuery: 'Hedera helix ivy on wall',
    wikimediaSearch: 'Hedera helix',
    imageNotes: 'Hojas brillantes cubriendo muro.'
  },
  {
    id: 'romero',
    name: 'Romero',
    alias: 'Perfume de solar',
    guild: 'plantas',
    latin: 'Salvia rosmarinus',
    image: './img/species/romero.jpg',
    season: 'Floración invierno–primavera',
    where: 'Jardineras, medianas, Montjuïc y Collserola seco.',
    hook: 'Lo hueles antes de verlo.',
    signals: [
      'Hojas estrechas aromáticas',
      'Flores azul-lila pequeñas',
      'Porte leñoso bajo'
    ],
    tip: 'Frota una hoja: si huele a cocina mediterránea, es romero.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Nativo del Mediterráneo; omnipresente en jardinería seca.',
    sources: ['Flora Catalana'],
    imageQuery: 'Salvia rosmarinus rosemary flowers',
    wikimediaSearch: 'Salvia rosmarinus',
    imageNotes: 'Hojas lineales y flores azuladas.'
  },
  {
    id: 'buganvilla',
    name: 'Buganvilla',
    alias: 'Fuego en la reja',
    guild: 'plantas',
    latin: 'Bougainvillea',
    image: './img/species/buganvilla.jpg',
    season: 'Primavera–otoño (máximo en calor)',
    where: 'Balcones, patios soleados, pérgolas y muros al sol.',
    hook: 'Ese magenta imposible no es la flor: son brácteas.',
    signals: [
      'Brácteas de color intenso',
      'Espinas en el tallo',
      'Hojas ovales pequeñas'
    ],
    tip: 'Mira el centro de la “flor”: la flor de verdad es diminuta.',
    markKinds: ['vi'],
    confidence: 'medium',
    localNote: 'Más de patio y fachada que de parque municipal.',
    sources: ['Guías de jardinería urbana mediterránea'],
    imageQuery: 'Bougainvillea magenta bracts',
    wikimediaSearch: 'Bougainvillea',
    imageNotes: 'Brácteas magenta y tallo espinoso.'
  },
  {
    id: 'lavanda',
    name: 'Lavanda',
    alias: 'Morado de jardín',
    guild: 'plantas',
    latin: 'Lavandula',
    image: './img/species/lavanda.jpg',
    season: 'Floración junio–septiembre',
    where: 'Jardineras soleadas, plazas y macizos secos.',
    hook: 'Abejas + perfume. Alguien plantó belleza a propósito.',
    signals: [
      'Espigas moradas densas',
      'Hojas grises aromáticas',
      'Mata compacta'
    ],
    tip: 'Si hay zumbido constante encima, ya sabes por qué.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Muy usada en jardinería urbana mediterránea.',
    sources: ['Guías de flora ornamental urbana'],
    imageQuery: 'Lavandula purple flower spikes',
    wikimediaSearch: 'Lavandula',
    imageNotes: 'Espigas púrpura y follaje gris.'
  },
  {
    id: 'gordolobo',
    name: 'Gordolobo',
    alias: 'Antorcha del solar',
    guild: 'plantas',
    latin: 'Verbascum',
    image: './img/species/gordolobo.jpg',
    season: 'Floración junio–septiembre',
    where: 'Cunetas, solares, bordes de camino y Collserola alterado.',
    hook: 'Una vela amarilla donde “no hay nada”.',
    signals: [
      'Espiga alta de flores amarillas',
      'Hojas grandes y peludas',
      'Porte columnar de 1–2 m'
    ],
    tip: 'Toca la hoja: afelpada. Primer año solo roseta; al segundo, la vela.',
    markKinds: ['vi'],
    confidence: 'medium',
    localNote: 'Más de margen y solar que de acera cuidada.',
    sources: ['Flora Catalana / Verbascum'],
    imageQuery: 'Verbascum thapsus yellow flower spike',
    wikimediaSearch: 'Verbascum thapsus',
    imageNotes: 'Espiga amarilla alta y hojas vellosas.'
  },
  {
    id: 'gorrion',
    name: 'Gorrión común',
    alias: 'El del café',
    guild: 'aves',
    latin: 'Passer domesticus',
    image: './img/species/gorrion.jpg',
    season: 'Todo el año',
    where: 'Terrazas, plazas, tejados y cualquier migaja.',
    hook: 'El pájaro que dabas por supuesto. Ahora tiene nombre.',
    signals: [
      'Macho con babero negro',
      'Chirridos cortos y sociales',
      'Siempre cerca de gente'
    ],
    tip: 'Si comes fuera y algo pide pan, empieza por él.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Residente urbano total en BCN y Hospitalet.',
    sources: ['SEO/BirdLife', 'eBird Barcelona'],
    imageQuery: 'Passer domesticus house sparrow male',
    wikimediaSearch: 'Passer domesticus',
    imageNotes: 'Macho con babero; contexto urbano.'
  },
  {
    id: 'paloma-brava',
    name: 'Paloma bravía',
    alias: 'La de las plazas',
    guild: 'aves',
    latin: 'Columba livia (feral)',
    image: './img/species/paloma-brava.jpg',
    season: 'Todo el año',
    where: 'Plazas, cornisas, estaciones y edificios altos.',
    hook: 'Sí, también cuenta. Conocer lo obvio es el primer flex.',
    signals: [
      'Gris azulado con brillos en el cuello',
      'Arrullo grave',
      'Bandos en el suelo de las plazas'
    ],
    tip: 'Mira el cuello al sol: iridiscencias verdes y púrpura.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Población feral urbana, naturalizada en la ciudad desde hace mucho. No es “exótica invasora” al estilo cotorra; es paloma de ciudad.',
    sources: ['SEO/BirdLife', 'eBird'],
    imageQuery: 'Columba livia feral pigeon city',
    wikimediaSearch: 'Columba livia',
    imageNotes: 'Paloma urbana con cuello iridiscente.'
  },
  {
    id: 'urraca',
    name: 'Urraca',
    alias: 'Blanco y negro con plan',
    guild: 'aves',
    latin: 'Pica pica',
    image: './img/species/urraca.jpg',
    season: 'Todo el año',
    where: 'Parques arbolados, Ciutadella, Collserola bajo.',
    hook: 'Larga cola, contraste brutal, cero disimulo.',
    signals: [
      'Blanco y negro nítido',
      'Cola muy larga con brillo',
      'Graznido seco y repetido'
    ],
    tip: 'Si algo brilla y desaparece, sospecha de ella.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Común en parques grandes y borde de Collserola.',
    sources: ['eBird', 'SEO/BirdLife'],
    imageQuery: 'Pica pica magpie long tail',
    wikimediaSearch: 'Pica pica',
    imageNotes: 'Perfil blanco-negro y cola larga.'
  },
  {
    id: 'cotorra-argentina',
    name: 'Cotorra argentina',
    alias: 'El ruido verde',
    guild: 'aves',
    latin: 'Myiopsitta monachus',
    image: './img/species/cotorra-argentina.jpg',
    season: 'Todo el año',
    where: 'Avenidas con árboles altos, parques y nidos comunales.',
    hook: 'Ese chillido que no es “pájaro de toda la vida”: es ella, y ya es de aquí.',
    signals: [
      'Verde lima con pecho grisáceo',
      'Gritos agudos en grupo',
      'Nidos enormes de palitos'
    ],
    tip: 'Busca “fortalezas” de ramas en lo alto de árboles o torres.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Especie introducida e invasora establecida en el área metropolitana. Observa; no alimentes.',
    sources: ['SEO/BirdLife', 'Documentación AMB / seguimiento urbano'],
    imageQuery: 'Myiopsitta monachus monk parakeet nest',
    wikimediaSearch: 'Myiopsitta monachus',
    imageNotes: 'Ave verde y nido comunal si aparece.'
  },
  {
    id: 'mirlo',
    name: 'Mirlo',
    alias: 'El flautista del parque',
    guild: 'aves',
    latin: 'Turdus merula',
    image: './img/species/mirlo.jpg',
    season: 'Todo el año',
    where: 'Parques, jardines y césped con lombrices.',
    hook: 'Negro, pico naranja, canción de atardecer.',
    signals: [
      'Macho negro con pico naranja',
      'Canto melódico al alba/atardecer',
      'Salta por el césped'
    ],
    tip: 'A última hora, para y escucha: suele ser el primero que oyes.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Residente habitual en parques de BCN y Hospitalet.',
    sources: ['eBird', 'SEO/BirdLife'],
    imageQuery: 'Turdus merula male orange beak',
    wikimediaSearch: 'Turdus merula',
    imageNotes: 'Macho negro con pico naranja.'
  },
  {
    id: 'carbonero-comun',
    name: 'Carbonero común',
    alias: 'Corbata amarilla',
    guild: 'aves',
    latin: 'Parus major',
    image: './img/species/carbonero-comun.jpg',
    season: 'Todo el año',
    where: 'Parques arbolados, Collserola y jardines con cobertura.',
    hook: 'Pequeño, nervioso y con corbata negra sobre pecho claro.',
    signals: [
      'Cabeza negra y mejillas blancas',
      'Banda oscura en el pecho',
      'Llamada metálica corta'
    ],
    tip: 'Mira ramas medias, no el cielo abierto.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Común y adaptable al arbolado urbano.',
    sources: ['eBird', 'SEO/BirdLife'],
    imageQuery: 'Parus major great tit',
    wikimediaSearch: 'Parus major',
    imageNotes: 'Cabeza negra, mejillas blancas, pecho con banda.'
  },
  {
    id: 'verdecillo',
    name: 'Verdecillo',
    alias: 'Canario de barrio',
    guild: 'aves',
    latin: 'Serinus serinus',
    image: './img/species/verdecillo.jpg',
    season: 'Todo el año',
    where: 'Parques, pinos y árboles con semilla (también tipuanas/jacarandás).',
    hook: 'Canto eléctrico. Verde limón si le da el sol.',
    signals: [
      'Pequeño y verdoso-amarillo',
      'Canto rápido y metálico',
      'A menudo en lo alto'
    ],
    tip: 'Si “suena a canario barato y feliz”, es verdecillo.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Residente frecuente en zona metro.',
    sources: ['eBird', 'SEO/BirdLife'],
    imageQuery: 'Serinus serinus european serin',
    wikimediaSearch: 'Serinus serinus',
    imageNotes: 'Pequeño pájaro verde-amarillo.'
  },
  {
    id: 'golondrina-comun',
    name: 'Golondrina común',
    alias: 'Verano en vuelo',
    guild: 'aves',
    latin: 'Hirundo rustica',
    image: './img/species/golondrina-comun.jpg',
    season: 'Primavera–otoño (migrante)',
    where: 'Cielos abiertos, cerca de agua y aleros con nidos de barro.',
    hook: 'Cola de tijera. Cuando vuelve, el barrio cambia de estación.',
    signals: [
      'Cola muy ahorquillada',
      'Garganta rojiza',
      'Vuelo bajo cazando insectos'
    ],
    tip: 'No confundir con el avión: la golondrina lleva “colas largas”.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Migrante; primavera–verano es su temporada visible.',
    sources: ['eBird', 'SEO/BirdLife'],
    imageQuery: 'Hirundo rustica barn swallow forked tail',
    wikimediaSearch: 'Hirundo rustica',
    imageNotes: 'Vuelo con cola bifurcada y pecho rojizo.'
  },
  {
    id: 'cernicalo',
    name: 'Cernícalo vulgar',
    alias: 'El que cuelga en el aire',
    guild: 'aves',
    latin: 'Falco tinnunculus',
    image: './img/species/cernicalo.jpg',
    season: 'Todo el año',
    where: 'Cielos abiertos, Collserola, descampados y a veces cornisas altas.',
    hook: 'Se queda quieto aleteando. Halcón de ciudad a escala íntima.',
    signals: [
      'Cernido fijo en el aire',
      'Dorso rojizo moteado (macho con cabeza más gris)',
      'Cola relativamente larga'
    ],
    tip: 'Si ves un pájaro “colgado” sin avanzar, mira dos veces.',
    markKinds: ['vi', 'oi'],
    confidence: 'high',
    localNote: 'Residente adaptable; más fácil en bordes y espacios abiertos.',
    sources: ['eBird', 'SEO/BirdLife'],
    imageQuery: 'Falco tinnunculus hovering kestrel',
    wikimediaSearch: 'Falco tinnunculus',
    imageNotes: 'Cernido en el aire o posado en cornisa.'
  },
  {
    id: 'ruisenor',
    name: 'Ruiseñor',
    alias: 'El que canta de noche',
    guild: 'aves',
    latin: 'Luscinia megarhynchos',
    image: './img/species/ruisenor.jpg',
    season: 'Primavera–verano',
    where: 'Sotobosque denso: Collserola, parques maduros y riberas.',
    hook: 'Si de noche algo ensaya una ópera, puede ser él.',
    signals: [
      'Canto potente y variado',
      'Pájaro marrón discreto (difícil de ver)',
      'Prefiere matorral denso'
    ],
    tip: 'Más oído que vista. Hospitalet lo tiene cerca vía parques y Collserola.',
    markKinds: ['oi', 'vi'],
    confidence: 'medium',
    localNote: 'No es el pájaro de la plaza dura; busca cobertura vegetal. Vale la pena dejarlo: es el ejemplo perfecto del pitch.',
    sources: ['eBird Collserola / Barcelona', 'SEO/BirdLife'],
    imageQuery: 'Luscinia megarhynchos nightingale',
    wikimediaSearch: 'Luscinia megarhynchos',
    imageNotes: 'Ave discreta marrón; mejor con contexto de matorral.'
  },
  {
    id: 'lagartija-catalana',
    name: 'Lagartija catalana',
    alias: 'Flash en el muro',
    guild: 'otros',
    latin: 'Podarcis liolepis',
    image: './img/species/lagartija-catalana.jpg',
    season: 'Primavera–otoño',
    where: 'Muros soleados, rocas, Montjuïc y Collserola.',
    hook: 'Un destello y se acabó. Bienvenida a mirar el suelo.',
    signals: [
      'Pequeña y rapidísima',
      'Cola larga',
      'Soleándose en piedra o muro'
    ],
    tip: 'Media mañana, muro al sol: escenario favorito.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'En Catalunya el complejo de “lagartija ibérica” se trata hoy a menudo como Podarcis liolepis. Ficha de campo: lagartija de pared soleada.',
    sources: ['SECEM / herpetofauna ibérica', 'Atlas locales'],
    imageQuery: 'Podarcis liolepis wall lizard',
    wikimediaSearch: 'Podarcis liolepis',
    imageNotes: 'Lagartija pequeña en muro soleado.'
  },
  {
    id: 'erizo-europeo',
    name: 'Erizo europeo',
    alias: 'Bola de noche',
    guild: 'otros',
    latin: 'Erinaceus europaeus',
    image: './img/species/erizo-europeo.jpg',
    season: 'Primavera–otoño',
    where: 'Jardines con hojarasca, bordes de Collserola y parques con refugio.',
    hook: 'No es un mito rural: aún cruza la noche metropolitana.',
    signals: [
      'Cuerpo cubierto de púas',
      'Andar decidido y bajo',
      'Actividad nocturna'
    ],
    tip: 'Si lo ves, celebra en silencio y deja paso. Nada de flash a quemarropa.',
    markKinds: ['vi'],
    confidence: 'medium',
    localNote: 'Presente pero sensible a fragmentación y venenos. Más fácil en bordes que en asfalto puro.',
    sources: ['Atlas de biodiversidad urbana', 'Fichas fauna local'],
    imageQuery: 'Erinaceus europaeus hedgehog',
    wikimediaSearch: 'Erinaceus europaeus',
    imageNotes: 'Erizo en contexto de jardín/hojarasca.'
  },
  {
    id: 'murcielago-enano',
    name: 'Murciélago enano',
    alias: 'Píxel del anochecer',
    guild: 'otros',
    latin: 'Pipistrellus pipistrellus / P. pygmaeus',
    image: './img/species/murcielago-enano.jpg',
    season: 'Primavera–otoño',
    where: 'Cielos al atardecer sobre plazas, parques y farolas.',
    hook: 'No es un pájaro raro: es mamífero a toda pastilla comiendo mosquitos.',
    signals: [
      'Vuelo errático al crepúsculo',
      'Silueta pequeña alrededor de luces',
      'Sin canto de ave'
    ],
    tip: 'Cinco minutos mirando arriba al anochecer bastan para pillarlo.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'En ciudad los pipistrellus son los habituales; separar pipistrellus/pygmaeus a ojo es casi imposible. Ficha de encuentro: murciélago pequeño urbano.',
    sources: ['ratpenats.org', 'Gencat fauna', 'SECEM'],
    imageQuery: 'Pipistrellus pipistrellus bat dusk',
    wikimediaSearch: 'Pipistrellus pipistrellus',
    imageNotes: 'Murciélago pequeño; preferible silueta crepuscular.'
  },
  {
    id: 'abeja-miel',
    name: 'Abeja de la miel',
    alias: 'La de la lavanda',
    guild: 'otros',
    latin: 'Apis mellifera',
    image: './img/species/abeja-miel.jpg',
    season: 'Primavera–otoño',
    where: 'Flores urbanas: romero, lavanda, tipuana, jacarandá…',
    hook: 'Sin ella, el barrio florece menos. Crédito donde corresponde.',
    signals: [
      'Rayas y pelusa',
      'Vuelo de flor en flor',
      'Zumbido grave'
    ],
    tip: 'No todas las “abejas” lo son: las avispas son otro rollo.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Habitual en floraciones urbanas; fundamental como polinizadora.',
    sources: ['Guías de polinizadores urbanos'],
    imageQuery: 'Apis mellifera honey bee on flower',
    wikimediaSearch: 'Apis mellifera',
    imageNotes: 'Abeja en flor, con polen si puede.'
  },
  {
    id: 'mariposa-blanca-col',
    name: 'Blanca de la col',
    alias: 'Mariposa de mediodía',
    guild: 'otros',
    latin: 'Pieris rapae',
    image: './img/species/mariposa-blanca-col.jpg',
    season: 'Primavera–otoño',
    where: 'Parques, huertos urbanos y cualquier esquina soleada.',
    hook: 'La mariposa blanca que cruzó tu camino mil veces sin nombre.',
    signals: [
      'Alas blancas con puntitos negros',
      'Vuelo blandito y bajo',
      'Sobre flores y crucíferas'
    ],
    tip: 'Si es blanca, pequeña y urbana, suele ser esta.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'De las mariposas más fáciles de ver en la ciudad.',
    sources: ['Guías de lepidópteros comunes'],
    imageQuery: 'Pieris rapae small white butterfly',
    wikimediaSearch: 'Pieris rapae',
    imageNotes: 'Mariposa blanca con puntos negros.'
  },
  {
    id: 'caracol-comun',
    name: 'Caracol común',
    alias: 'El lento del riego',
    guild: 'otros',
    latin: 'Cornu aspersum',
    image: './img/species/caracol-comun.jpg',
    season: 'Tras lluvia o riego',
    where: 'Jardines, macetas, paredes húmedas.',
    hook: 'Aparece cuando la ciudad se moja. Ritmo anti-metro.',
    signals: [
      'Concha espiral moteada',
      'Rastro plateado',
      'Activo con humedad'
    ],
    tip: 'Después de llover, mira macetas y bordillos.',
    markKinds: ['vi'],
    confidence: 'high',
    localNote: 'Muy común en jardinería húmeda.',
    sources: ['Fichas de moluscos comunes'],
    imageQuery: 'Cornu aspersum garden snail',
    wikimediaSearch: 'Cornu aspersum',
    imageNotes: 'Concha espiral y cuerpo en hoja/muro.'
  }
];

window.ENTORNO_GUILDS = [
  { id: 'all', label: 'Todos' },
  { id: 'arboles', label: 'Árboles' },
  { id: 'plantas', label: 'Plantas' },
  { id: 'aves', label: 'Aves' },
  { id: 'otros', label: 'Otros' }
];
